apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: alpine:3.5
        command:
        - /bin/sh
        - -c
        - "while :; do echo 'Hello'; sleep 1; done"
